version: '3'

services:
  api:
    build: backend/
    depends_on:
      - 'database'
    volumes:
      - './backend:/src/app'
      - '/src/app/node_modules'

    ports: 
      - '3005:3005'

  client:
    build: frontend/sights-to-see
    depends_on:
      - 'database'
      - 'api'
    environment:
        PORT: 3004
    volumes:
      - './frontend/sights-to-see:/web'
      - '/web/node_modules'
    ports:
      - '3004:3004'
    stdin_open: true

  database:
    build: database/
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      
